### PR TITLE
Update to MSBuild/V2022 and clickable data collection fixes

### PR DESCRIPTION
**Pull request by mcphailtom**
- Updated Lua to 5.4.6
- extract_clickabledata.lua updated to use table.unpack() instead of deprecated unpack (was no longer working for some modules since 2.9.1.48335 update e.g. F-15E)
- modified build_plugin.bat to use MSBuild and copy runtime/lua DLLs
- Lua and JSON managed with NuGet

### CODE REVIEW

**Comment by mcphailtom** [comment]
seems like the build action never actually ran

**Comment by mcphailtom** [comment]
I am using this version myself. The sln opens in VSCE 2022 and compiles cleanly with the only real functional difference being the lua library and minor change to the clickable data collection lua script.

**Comment by charlestytler** [comment]
> seems like the build action never actually ran

Thanks for putting up the PR! I was just looking at my github actions and pushed an update to the triggers on master so I think it might work better with pull requests -- this is my first external PR on this repo so still learning 😄. If you don't mind merging in master I think it will run them. Otherwise, I can update my MSBuild version and test on my machine this weekend before merging.

One other nitpick: I've tried to exclude `*.vcxproj.user` files in my `.gitignore`, do you have any idea why that didn't work on your PR?

Changes look good to me other than that.

**Comment by mcphailtom** [comment]
Hey @charlestytler no worries at all and thanks for taking a peek. I'll have a look at the .gitignore this afternoon and fix that up with an update. I think it would require at least a review from you for me to merge otherwise.

**Comment by mcphailtom** [comment]
Updated 👍

**Comment by mcphailtom** [comment]
Will probably need to update actions to run the newer MSBuild

**Comment by charlestytler** [comment]
I added on a couple commits to get the action working again, and fixed the setup so NuGet packages are restored fresh as part of the build process. This PR was incorporated in with #129

**Pull request merged**
